name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend
        run: docker build -t smart-backend ./backend

      - name: Build frontend
        run: docker build -t smart-frontend ./frontend

      - name: Build sensor-simulator
        run: docker build -t smart-sensor-simulator ./sensor-simulator
