apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-backend
  template:
    metadata:
      labels:
        app: smart-backend
    spec:
      containers:
        - name: backend
          image: smart-office-monitor-backend:latest
          ports:
            - containerPort: 5000
